// Generated by gencpp from file xf_mic_asr_offline/Set_Major_Mic_srvRequest.msg
// DO NOT EDIT!


#ifndef XF_MIC_ASR_OFFLINE_MESSAGE_SET_MAJOR_MIC_SRVREQUEST_H
#define XF_MIC_ASR_OFFLINE_MESSAGE_SET_MAJOR_MIC_SRVREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace xf_mic_asr_offline
{
template <class ContainerAllocator>
struct Set_Major_Mic_srvRequest_
{
  typedef Set_Major_Mic_srvRequest_<ContainerAllocator> Type;

  Set_Major_Mic_srvRequest_()
    : mic_id(0)  {
    }
  Set_Major_Mic_srvRequest_(const ContainerAllocator& _alloc)
    : mic_id(0)  {
  (void)_alloc;
    }



   typedef int8_t _mic_id_type;
  _mic_id_type mic_id;





  typedef boost::shared_ptr< ::xf_mic_asr_offline::Set_Major_Mic_srvRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::xf_mic_asr_offline::Set_Major_Mic_srvRequest_<ContainerAllocator> const> ConstPtr;

}; // struct Set_Major_Mic_srvRequest_

typedef ::xf_mic_asr_offline::Set_Major_Mic_srvRequest_<std::allocator<void> > Set_Major_Mic_srvRequest;

typedef boost::shared_ptr< ::xf_mic_asr_offline::Set_Major_Mic_srvRequest > Set_Major_Mic_srvRequestPtr;
typedef boost::shared_ptr< ::xf_mic_asr_offline::Set_Major_Mic_srvRequest const> Set_Major_Mic_srvRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::xf_mic_asr_offline::Set_Major_Mic_srvRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::xf_mic_asr_offline::Set_Major_Mic_srvRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::xf_mic_asr_offline::Set_Major_Mic_srvRequest_<ContainerAllocator1> & lhs, const ::xf_mic_asr_offline::Set_Major_Mic_srvRequest_<ContainerAllocator2> & rhs)
{
  return lhs.mic_id == rhs.mic_id;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::xf_mic_asr_offline::Set_Major_Mic_srvRequest_<ContainerAllocator1> & lhs, const ::xf_mic_asr_offline::Set_Major_Mic_srvRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace xf_mic_asr_offline

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::xf_mic_asr_offline::Set_Major_Mic_srvRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::xf_mic_asr_offline::Set_Major_Mic_srvRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::xf_mic_asr_offline::Set_Major_Mic_srvRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::xf_mic_asr_offline::Set_Major_Mic_srvRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::xf_mic_asr_offline::Set_Major_Mic_srvRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::xf_mic_asr_offline::Set_Major_Mic_srvRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::xf_mic_asr_offline::Set_Major_Mic_srvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7f380dfab200f6a5cd81c0b74e87b242";
  }

  static const char* value(const ::xf_mic_asr_offline::Set_Major_Mic_srvRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7f380dfab200f6a5ULL;
  static const uint64_t static_value2 = 0xcd81c0b74e87b242ULL;
};

template<class ContainerAllocator>
struct DataType< ::xf_mic_asr_offline::Set_Major_Mic_srvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "xf_mic_asr_offline/Set_Major_Mic_srvRequest";
  }

  static const char* value(const ::xf_mic_asr_offline::Set_Major_Mic_srvRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::xf_mic_asr_offline::Set_Major_Mic_srvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int8 mic_id\n"
;
  }

  static const char* value(const ::xf_mic_asr_offline::Set_Major_Mic_srvRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::xf_mic_asr_offline::Set_Major_Mic_srvRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.mic_id);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Set_Major_Mic_srvRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::xf_mic_asr_offline::Set_Major_Mic_srvRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::xf_mic_asr_offline::Set_Major_Mic_srvRequest_<ContainerAllocator>& v)
  {
    s << indent << "mic_id: ";
    Printer<int8_t>::stream(s, indent + "  ", v.mic_id);
  }
};

} // namespace message_operations
} // namespace ros

#endif // XF_MIC_ASR_OFFLINE_MESSAGE_SET_MAJOR_MIC_SRVREQUEST_H
