// Generated by gencpp from file orbbec_camera/GetString.msg
// DO NOT EDIT!


#ifndef ORBBEC_CAMERA_MESSAGE_GETSTRING_H
#define ORBBEC_CAMERA_MESSAGE_GETSTRING_H

#include <ros/service_traits.h>


#include <orbbec_camera/GetStringRequest.h>
#include <orbbec_camera/GetStringResponse.h>


namespace orbbec_camera
{

struct GetString
{

typedef GetStringRequest Request;
typedef GetStringResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetString
} // namespace orbbec_camera


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::orbbec_camera::GetString > {
  static const char* value()
  {
    return "15baad3d82a7b70bfc4eb31d66322293";
  }

  static const char* value(const ::orbbec_camera::GetString&) { return value(); }
};

template<>
struct DataType< ::orbbec_camera::GetString > {
  static const char* value()
  {
    return "orbbec_camera/GetString";
  }

  static const char* value(const ::orbbec_camera::GetString&) { return value(); }
};


// service_traits::MD5Sum< ::orbbec_camera::GetStringRequest> should match
// service_traits::MD5Sum< ::orbbec_camera::GetString >
template<>
struct MD5Sum< ::orbbec_camera::GetStringRequest>
{
  static const char* value()
  {
    return MD5Sum< ::orbbec_camera::GetString >::value();
  }
  static const char* value(const ::orbbec_camera::GetStringRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::orbbec_camera::GetStringRequest> should match
// service_traits::DataType< ::orbbec_camera::GetString >
template<>
struct DataType< ::orbbec_camera::GetStringRequest>
{
  static const char* value()
  {
    return DataType< ::orbbec_camera::GetString >::value();
  }
  static const char* value(const ::orbbec_camera::GetStringRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::orbbec_camera::GetStringResponse> should match
// service_traits::MD5Sum< ::orbbec_camera::GetString >
template<>
struct MD5Sum< ::orbbec_camera::GetStringResponse>
{
  static const char* value()
  {
    return MD5Sum< ::orbbec_camera::GetString >::value();
  }
  static const char* value(const ::orbbec_camera::GetStringResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::orbbec_camera::GetStringResponse> should match
// service_traits::DataType< ::orbbec_camera::GetString >
template<>
struct DataType< ::orbbec_camera::GetStringResponse>
{
  static const char* value()
  {
    return DataType< ::orbbec_camera::GetString >::value();
  }
  static const char* value(const ::orbbec_camera::GetStringResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ORBBEC_CAMERA_MESSAGE_GETSTRING_H
