// Generated by gencpp from file orbbec_camera/SetString.msg
// DO NOT EDIT!


#ifndef ORBBEC_CAMERA_MESSAGE_SETSTRING_H
#define ORBBEC_CAMERA_MESSAGE_SETSTRING_H

#include <ros/service_traits.h>


#include <orbbec_camera/SetStringRequest.h>
#include <orbbec_camera/SetStringResponse.h>


namespace orbbec_camera
{

struct SetString
{

typedef SetStringRequest Request;
typedef SetStringResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetString
} // namespace orbbec_camera


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::orbbec_camera::SetString > {
  static const char* value()
  {
    return "546971982e3fbbd5a41e60fb6432e357";
  }

  static const char* value(const ::orbbec_camera::SetString&) { return value(); }
};

template<>
struct DataType< ::orbbec_camera::SetString > {
  static const char* value()
  {
    return "orbbec_camera/SetString";
  }

  static const char* value(const ::orbbec_camera::SetString&) { return value(); }
};


// service_traits::MD5Sum< ::orbbec_camera::SetStringRequest> should match
// service_traits::MD5Sum< ::orbbec_camera::SetString >
template<>
struct MD5Sum< ::orbbec_camera::SetStringRequest>
{
  static const char* value()
  {
    return MD5Sum< ::orbbec_camera::SetString >::value();
  }
  static const char* value(const ::orbbec_camera::SetStringRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::orbbec_camera::SetStringRequest> should match
// service_traits::DataType< ::orbbec_camera::SetString >
template<>
struct DataType< ::orbbec_camera::SetStringRequest>
{
  static const char* value()
  {
    return DataType< ::orbbec_camera::SetString >::value();
  }
  static const char* value(const ::orbbec_camera::SetStringRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::orbbec_camera::SetStringResponse> should match
// service_traits::MD5Sum< ::orbbec_camera::SetString >
template<>
struct MD5Sum< ::orbbec_camera::SetStringResponse>
{
  static const char* value()
  {
    return MD5Sum< ::orbbec_camera::SetString >::value();
  }
  static const char* value(const ::orbbec_camera::SetStringResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::orbbec_camera::SetStringResponse> should match
// service_traits::DataType< ::orbbec_camera::SetString >
template<>
struct DataType< ::orbbec_camera::SetStringResponse>
{
  static const char* value()
  {
    return DataType< ::orbbec_camera::SetString >::value();
  }
  static const char* value(const ::orbbec_camera::SetStringResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ORBBEC_CAMERA_MESSAGE_SETSTRING_H
